#!/usr/bin/env ruby

require 'open-uri'
require 'json'
require 'yaml'

config = YAML.safe_load(File.open("#{ENV['HOME']}/.config/i3blocks/scripts/config.yml"))['surf']

hour = Time.now.hour
# 3 API requests to get 3 pieces of data. sadness
temp_response = JSON.parse(open("#{config['base']}#{config['water_temp_endpoint']}#{config['county']}").read)

tide_response = JSON.parse(open("#{config['base']}#{config['tide_endpoint']}#{config['county']}").read)

spot_response = JSON.parse(open("#{config['base']}#{config['spot_forecast_endpoint']}#{config['spot_id']}").read)

tide = tide_response[hour]['tide'].round(1)
tide_next_hour = tide_response[hour+1]['tide']
tide_icon =
  if tide < tide_next_hour
    # up arrow
    ''
  else
    # down arrow
    ''
  end


size = spot_response[hour]['size']
name = spot_response[0]['spot_name']

print "#{name}: #{size}ft #{temp_response['fahrenheit']}F #{tide}#{tide_icon}".force_encoding(Encoding::BINARY)
