#!/usr/bin/env ruby

require 'open-uri'
require 'json'
require 'yaml'

config = YAML.safe_load(File.open("#{ENV['HOME']}/.config/i3blocks/scripts/config.yml"))['weather']

begin
  response = JSON.parse(open("#{config['base']}zip=#{config['zipcode']}&units=imperial&APPID=#{config['apikey']}").read)

  description = response['weather'][0]['main']

  temp = Integer(response['main']['temp'].ceil)
  color = case temp
            when 0..65 then '#268bd2'
            when 66..80 then '#b58900'
            when 81..105 then '#dc322f'
          end

  print "<span foreground='#{color}'>#{description} #{temp}F</span>".force_encoding(Encoding::BINARY)
  exit 0
rescue
  exit 0
end
