#!/bin/sh
# for testing dunst changes. Thanks to: https://raw.githubusercontent.com/Kaligule/dunst-config/master/reload
pkill dunst
dunst -config ~/.config/dunst/dunstrc &

notify-send -u critical "Test message: critical test 1"
notify-send -u normal "Test message: normal test 2"
notify-send -u normal "Test message: normal test 2. But with much more text than usual to see how things wrap, shrink,
recoil in horror, wet the bed, etc. Plus goats"
notify-send -u low "Test message: low test 3"
notify-send -u critical "Test message: critical test 4"
notify-send -u normal "Test message: normal test 5"
notify-send -u low "Test message: low test 6"
notify-send -u critical "Test message: critical test 7"
notify-send -u normal "Test message: normal test 8"
notify-send -u low "Test message: low test 9"
