#!/bin/sh
TMUX_PROJECT_PATH="$HOME/projects/ucsd/dewey"
tmux new-session -s dewey -n vim -d
tmux send-keys -t dewey "cd $TMUX_PROJECT_PATH" C-m
tmux send-keys -t dewey 'vim' C-m
tmux new-window -t dewey
tmux send-keys -t dewey:2 "cd $TMUX_PROJECT_PATH" C-m
tmux new-window -n puma-server -t dewey
tmux send-keys -t dewey:3 "cd $TMUX_PROJECT_PATH" C-m
tmux select-window -t dewey:1
tmux attach -t dewey
unset TMUX_PROJECT_PATH
