#!bin/bash
# VI mode and settings
set editing-mode vi
set show-mode-in-prompt on
set vi-ins-mode-string \1\e[6 q\2
set vi-cmd-mode-string \1\e[2 q\2

set meta-flag on
set input-meta on
set convert-meta off
set output-meta on

set mark-symlinked-directories on
set bell-style visible
set completion-ignore-case on
set show-all-if-ambiguous on

