#!/bin/sh

if [ ! -d "$HOME"/.vim/pack/minpac/opt ]; then
  mkdir -p ~/.vim/pack/minpac/opt
  cd ~/.vim/pack/minpac/opt || exit
  git clone https://github.com/k-takata/minpac.git
fi
vim -u "$HOME"/.vimrc +PackUpdate +PackClean +qa

# Gimme my terminal back plz
reset -Q
