#!/bin/sh
TMUX_PROJECT_PATH="$HOME/projects/personal/dotfiles/"
tmux new-session -s dots -n vim -d
tmux send-keys -t dots "cd $TMUX_PROJECT_PATH" C-m
tmux send-keys -t dots 'vim +Files' C-m
tmux new-window -n terminal -t dots
tmux send-keys -t dots:2 "cd $TMUX_PROJECT_PATH" C-m
tmux select-window -t dots:1
tmux attach -t dots
unset TMUX_PROJECT_PATH
