#!/bin/sh
TMUX_PROJECT_PATH="~/projects/ucsd/hifive/"
tmux new-session -s H5 -n vim -d
tmux send-keys -t H5 "cd $TMUX_PROJECT_PATH" C-m
tmux send-keys -t H5 'vim +Files' C-m
tmux new-window -n docker -t H5
tmux send-keys -t H5:2 "cd $TMUX_PROJECT_PATH" C-m
tmux send-keys -t H5:2 'docker-compose build' C-m
tmux new-window -n rails-console -t H5
tmux send-keys -t H5:3 "cd $TMUX_PROJECT_PATH" C-m
tmux select-window -t H5:1
tmux attach -t H5
unset TMUX_PROJECT_PATH
