live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

# [colors]
# draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#EFF1F5"
foreground = "#4C4F69"
dim_foreground = "#4C4F69"
bright_foreground = "#4C4F69"

[colors.cursor]
text = "#EFF1F5"
cursor = "#DC8A78"

[colors.vi_mode_cursor]
text = "#EFF1F5"
cursor = "#7287FD"

[colors.search.matches]
foreground = "#EFF1F5"
background = "#6C6F85"

[colors.search.focused_match]
foreground = "#EFF1F5"
background = "#40A02B"

[colors.footer_bar]
foreground = "#EFF1F5"
background = "#6C6F85"

[colors.hints.start]
foreground = "#EFF1F5"
background = "#DF8E1D"

[colors.hints.end]
foreground = "#EFF1F5"
background = "#6C6F85"

[colors.selection]
text = "#EFF1F5"
background = "#DC8A78"

[colors.normal]
black = "#5C5F77"
red = "#D20F39"
green = "#40A02B"
yellow = "#DF8E1D"
blue = "#1E66F5"
magenta = "#EA76CB"
cyan = "#179299"
white = "#ACB0BE"

[colors.bright]
black = "#6C6F85"
red = "#D20F39"
green = "#40A02B"
yellow = "#DF8E1D"
blue = "#1E66F5"
magenta = "#EA76CB"
cyan = "#179299"
white = "#BCC0CC"

[colors.dim]
black = "#5C5F77"
red = "#D20F39"
green = "#40A02B"
yellow = "#DF8E1D"
blue = "#1E66F5"
magenta = "#EA76CB"
cyan = "#179299"
white = "#ACB0BE"

[[colors.indexed_colors]]
index = 16
color = "#FE640B"

[[colors.indexed_colors]]
index = 17
color = "#DC8A78"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
persistent_logging = false
render_timer = false

[font]
size = 13

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "G", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
# opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
