k9s:
  ui:
    skin: catppuccin-latte
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 1000
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: lib-k8s-np-a
  currentCluster: lib-k8s-np-a
  keepMissingClusters: false
  clusters:
    lib-k8s-a:
      namespace:
        active: highfive-prod
        lockFavorites: false
        favorites:
        - highfive-prod
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    lib-k8s-np-a:
      namespace:
        active: tidewater-review
        lockFavorites: false
        favorites:
        - tidewater-review
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-mcritchlow
  disablePodCounting: false
