# K9s Github Light Skin Contributed by [@indiebrain](https://github.com/indiebrain)
foreground: &foreground "#586069"
background: &background "#ffffff"
current_line: &current_line "#FCFCFA"
selection: &selection "#3c3735"
comment: &comment "#bdad93"
cyan: &cyan "#0598BC"
yellow: &yellow "#949800"
green: &green "#14ce14"
orange: &orange "#d79920"
magenta: &magenta "#bc05bc"
blue: &blue "#0451a5"
red: &red "#d03d3d"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *blue
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *orange
  info:
    fgColor: *magenta
    sectionColor: *foreground
  help:
    fgColor: *foreground
    bgColor: *background
    keyColor: *magenta
    numKeyColor: *blue
    sectionColor: *green
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *magenta
    buttonFocusFgColor: white
    buttonFocusBgColor: *cyan
    labelFgColor: *orange
    fieldFgColor: *foreground
  frame:
    border:
      fgColor: *selection
      focusColor: *current_line
    menu:
      fgColor: *foreground
      keyColor: *magenta
      numKeyColor: *magenta
    crumbs:
      fgColor: *foreground
      bgColor: *comment
      activeColor: *blue
    status:
      newColor: *cyan
      modifyColor: *blue
      addColor: *green
      errorColor: *red
      highlightColor: *orange
      killColor: *comment
      completedColor: *comment
    title:
      fgColor: *foreground
      bgColor: *background
      highlightColor: *orange
      counterColor: *blue
      filterColor: *magenta
  views:
    charts:
      bgColor: background
      defaultDialColors:
        - *blue
        - *red
      defaultChartColors:
        - *blue
        - *red
    table:
      fgColor: *foreground
      bgColor: *background
      cursorFgColor: *foreground
      cursorBgColor: *current_line
      header:
        fgColor: *foreground
        bgColor: *background
        sorterColor: *selection
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *current_line
      graphicColor: *blue
      showIcons: false
    yaml:
      keyColor: *magenta
      colonColor: *blue
      valueColor: *foreground
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *background
