# K9s Github Light Skin
foreground: &foreground "#586069"
background: &background "#ffffff"
current_line: &current_line "#FCFCFA"
selection: &selection "#3c3735"
comment: &comment "#bdad93"
cyan: &cyan "#0598BC"
yellow: &yellow "#949800"
green: &green "#14ce14"
orange: &orange "#d79920"
magenta: &magenta "#bc05bc"
blue: &blue "#0451a5"
red: &red "#d03d3d"
background_visual: &background_visual "#dbe9f9"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *cyan
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *orange
  info:
    fgColor: *magenta
    sectionColor: *foreground
  help:
    fgColor: *foreground
    bgColor: *background
    keyColor: *magenta
    numKeyColor: *blue
    sectionColor: *green
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *magenta
    buttonFocusFgColor: *background
    buttonFocusBgColor: *cyan
    labelFgColor: *orange
    fieldFgColor: *foreground
  frame:
    border:
      fgColor: *selection
      focusColor: *background_visual
    menu:
      fgColor: *foreground
      keyColor: *magenta
      numKeyColor: *magenta
    crumbs:
      fgColor: *foreground
      bgColor: *background_visual
      activeColor: *cyan
    status:
      newColor: *yellow
      modifyColor: *blue
      addColor: *green
      errorColor: *red
      highlightColor: *orange
      killColor: *red
      completedColor: *green
    title:
      fgColor: *foreground
      bgColor: *background
      highlightColor: *orange
      counterColor: *blue
      filterColor: *magenta
  views:
    charts:
      bgColor: *background
      defaultDialColors:
        - *blue
        - *red
      defaultChartColors:
        - *blue
        - *red
    table:
      fgColor: *foreground
      bgColor: *background
      cursorFgColor: *foreground
      cursorBgColor: *background_visual
      header:
        fgColor: *foreground
        bgColor: *background
        sorterColor: *selection
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *background_visual
      graphicColor: *blue
      showIcons: false
    yaml:
      keyColor: *magenta
      colonColor: *blue
      valueColor: *foreground
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *background
